### ISSUE TITLE
Build Tasks on Context Menu

### ISSUE THREAD

**Issue by ddetton** [sentry07/vscode-crestron-splus#10]
I had a problem compiling at first but I think that it was because I was trying to do it without a folder open.  Once I fgured that, compiling works fine.  Is it possible to attach the build task(s) to the mouse right click context menu?  Not sure if this is something that I can do or not.  Still fairly new to VSCode.  Thanks for making this available.  Hoping to make this part of my standard workflow.

**Comment by sentry07** [comment]
0.4.2 released today introduces a feature that if you open just a single file, it will open the containing folder automatically so that you can use the build tasks. There is a lot of background stuff that VSCode has that supports build tasks, such as problem matching and dynamically generating tasks that I think benefit the user more than having a context menu shortcut. I think there will be a way to do build tasks while not in a folder in the future but VSCode doesn't support it yet.

**Comment by ddetton** [comment]
Thanks Eric!  Looks like I get the updates automatically because I have 0.4.2 now.  Once I get more up to speed on VS Code, I'll pitch in where I can.  You can close this out.
